### ISSUE TITLE
Not an issue 

### ISSUE THREAD

**Issue by Rozin14** [Irt291/RE315-API-Client#1]
Do you happen to find any way to install 3rd party firmware for RE315. Openwrt does have the 4MB flash limitation, but some people have "debloated" openwrt and kernel to save space and ran successfully. Openwrt can solve all issues.

**Comment by Irt291** [comment]
> Do you happen to find any way to install 3rd party firmware for RE315. Openwrt does have the 4MB flash limitation, but some people have "debloated" openwrt and kernel to save space and ran successfully. Openwrt can solve all issues.


Yes (but I haven't tried it yet). The RE315 comes with an 4-pin UART so maybe you can access the extender's root shell by connecting it to a computer. (Reference: [WikiDevi](https://wikidevi.wi-cat.ru/TP-LINK_RE315) and [FCCID](https://fcc.report/FCC-ID/TE7RE315))

Another approach is using TFTP, but it still too risky since there is no official OpenWrt firmware support for this device. Not to mention that it only has 4MB of flash memory. No one will waste their time on that crap and so do I.

Anyway, I enjoy reverse engineering the extender's web UI and its encryption process, it actually very fun and get things done for me.

PS:  I bought this crap for my dad to watch Netflix and it was my biggest reget. Maybe at some point, I will try the UART method if I have enough tools.

Have a nice day :))
